### ISSUE TITLE
Add local session in Guidance on Spark Sessions

### ISSUE THREAD

**Issue by AntonZogk** [best-practice-and-impact/ons-spark#124]
Should we add  some text encouraging when possible using local spark sessions, for example when developing code with small dummy or synthetic data or when using spark for training purposes.

**Comment by NathanKelly-ONS** [comment]
Closing this as we already have an issue for this, but good idea Anton!

**Comment by NathanKelly-ONS** [comment]
Closing it as "close as not planned" because "close as completed" suggests we've done the work which we haven't yet.
