### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by robertswh** [best-practice-and-impact/ons-spark#55]
apache spark have moved their docs, e.g.

The old link: https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.persist.html
The new link: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.persist.html

Need to change all links in the book to reflect this change.

**Comment by jkhall06** [comment]
Closing this as has now been dealt with.
