### ISSUE TITLE
add Ted Dolby's Spark ML for inference examples

### ISSUE THREAD

**Issue by robertswh** [best-practice-and-impact/ons-spark#56]
Ted presented some work on using Spark ML for inference, as is commonly done in ONS. We want to add that work and create PySpark example to go with his sparklyr examples

**Comment by emercado4** [comment]
I think this should have been closed when the logistic regression work was added but I'm not sure. @robertswh is it ok for this to be closed now?

**Comment by emercado4** [comment]
Closing this issue as I think it was addressed by the addition of the logistic regression page ([pull request](https://github.com/best-practice-and-impact/ons-spark/pull/84 )).
